export enum EVENTS {
  COMMAND_BLOCKED = "COMMAND_BLOCKED",
  COMMAND_CANCELLED = "COMMAND_CANCELLED",
  COMMAND_ERROR = "COMMAND_ERROR",
  COMMAND_FINISHED = "COMMAND_FINISHED",
  COMMAND_STARTED = "COMMAND_STARTED",
  CONNECT = "CONNECT",
  DEBUG = "DEBUG",
  DESTROY = "DESTROY",
  DISCONNECT = "DISCONNECT",
  ERROR = "ERROR",
  IDENTIFY = "IDENTIFY",
  INIT = "INIT",
  LOCKDOWN = "LOCKDOWN",
  MESSAGE_BLOCKED = "MESSAGE_BLOCKED",
  MUTE = "MUTE",
  READY = "READY",
  WARN = "WARN",
}

export default EVENTS;
