export enum TOPICS {
  APOLLO_CLIENT = "APOLLO_CLIENT",
  APOLLO_SERVER = "APOLLO_SERVER",
  DISCORD = "DISCORD",
  DISCORD_AKAIRO = "DISCORD_AKAIRO",
  METRICS = "METRICS",
  NEXUS = "NEXUS",
  RPC = "RPC",
  UNHANDLED_REJECTION = "UNHANDLED_REJECTION",
}

export default TOPICS;
